export default {
  promo: "",
  home: "board",
  admin: "admin",
  auth: {
    root: "auth",
    signIn: "",
    signUp: "sign-up",
    tokenSent: "email-sent",
    resetPassword: "reset-password",
    forgotPassword: "forgot-password",
    verifyAccount: "verify-account",
    verifyCode: "verify-code",
  },
  account: "account",
  profile: "profile",
  settings: "settings",
  notifications: "notifications",
  privacyPolicy: "privacy-policy",
  termsOfService: "terms-of-service",
  test: "test",
};
