import { TicketType } from "./Ticket";

export const testTickets: TicketType[] = [
  {
    title: "Configure system architecture",
    description: [
      "- Set up services in AWS",
      "- Point dns to new architecture",
      "- Deploy current project to new architecture",
    ],
    id: "1",
    createdAt: new Date(),
    updatedAt: new Date(),
    section: "ACTIVE",
    status: "UNASSIGNED",
    priority: "URGENT",
    timeEstimateMin: 600,
    projectId: "project-1",
    feature: { title: "Front end refactor", id: 1 },
    assignees: [],
  },
  {
    title: "Create authentication system",
    description: [
      "- Decide on authentication architecture (microservice or coded in)",
      "- Set up microservice or code authentication system in backend and sql (set up sql database)",
      "- Implement UI for login and registration",
      "- Time frame is an ballpark, but I don't expect it to take more than a long day's work",
    ],
    id: "1",
    createdAt: new Date(),
    updatedAt: new Date(),
    section: "ACTIVE",
    status: "UNASSIGNED",
    priority: "HIGH",
    timeEstimateMin: 480,
    projectId: "project-1",
    feature: { title: "Front end refactor", id: 1 },
    assignees: [],
  },
  {
    title: "Implement project database",
    description: [
      "- Partition project database",
      "- Migrate all current data to tables",
      "- Implement software architecture change to code",
      "- We will undboutably need this pretty quickly",
    ],
    id: "1",
    createdAt: new Date(),
    updatedAt: new Date(),
    section: "ACTIVE",
    status: "UNASSIGNED",
    priority: "HIGH",
    timeEstimateMin: 180,
    projectId: "project-1",
    feature: { title: "Front end refactor", id: 1 },
    assignees: [],
  },
  {
    title: "Front end refactor",
    description: [
      "- Remove environment config files and add to .gitignore",
      "- Upgrade create-react-app (react-scripts) to vite",
      "- Upgrade typescript to latest version",
    ],
    id: "1",
    createdAt: new Date(),
    updatedAt: new Date(),
    section: "ACTIVE",
    status: "UNASSIGNED",
    priority: "LOW",
    timeEstimateMin: 180,
    projectId: "project-1",
    feature: { title: "Front end refactor", id: 1 },
    assignees: [],
  },
  {
    title: "Scraping tools",
    description: [
      "- Set up cron job for exisiting scraping tools (I'm thinking AWS Lambda but we can discuss)",
      "- Build scraping tools for the other sites",
      "- Time frame on this is iffy. It depends on the complexity of the sites and how much data we need to scrape",
      "- AI says to expect this to take a few days to a week, but I believe it will be quicker",
    ],
    id: "1",
    createdAt: new Date(),
    updatedAt: new Date(),
    section: "ACTIVE",
    status: "UNASSIGNED",
    priority: "HIGH",
    timeEstimateMin: 720,
    projectId: "project-1",
    feature: { title: "Front end refactor", id: 1 },
    assignees: [],
  },
  {
    title: "AWS Lex Chatbot",
    description: [
      "- Create a custom AI chatbot using AWS Lex",
      "- Train LLM to only accept predetermined data",
      "- Time frame on this is unknown. After I take the course, I will have a better idea of how long this will take",
    ],
    id: "1",
    createdAt: new Date(),
    updatedAt: new Date(),
    section: "ACTIVE",
    status: "UNASSIGNED",
    priority: "MODERATE",
    timeEstimateMin: 600,
    projectId: "project-1",
    feature: { title: "Front end refactor", id: 1 },
    assignees: [],
  },
  {
    title: "Setup version control in project",
    description: ["- Set up versioning for scale"],
    id: "1",
    createdAt: new Date(),
    updatedAt: new Date(),
    section: "ACTIVE",
    status: "UNASSIGNED",
    priority: "MODERATE",
    timeEstimateMin: 120,
    projectId: "project-1",
    feature: { title: "Front end refactor", id: 1 },
    assignees: [],
  },
];
